before_install:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'sleep 3'
before_script:
  - 'npm install coffee-script'
  - 'sh compile-all.sh'
script: 'bundle exec rake jasmine:ci'
rvm:
  - '2.2'