before_install:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
before_script:
  - 'npm install coffee-script'
  - 'sh compile-all.sh'
  - 'ls javascripts/lib'
  -  'cat javascripts/lib/board.js'
script: 'DISPLAY=:99.0 rake jasmine:ci'

rvm:
  - '2.0'