before_install:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
before_script:
  - 'npm install coffee-script'
  - 'sh compile-all.sh'
  - "bundle update" # recommended for usage with caching without Gemfile.lock
script: 'DISPLAY=:99.0 rake jasmine:ci'
sudo: false
cache: bundler
rvm:
  - '2.2'