// Generated by CoffeeScript 1.6.2
var GO_STONE, scaleBoardTo19;

GO_STONE = "<div class='go-stone'></div>";

scaleBoardTo19 = function() {
  var stretchColumnsTo19, stretchRowsTo19;

  stretchRowsTo19 = function() {
    var duplicate, i, line, _i, _results;

    line = $('table.go-board tr:nth-child(2)');
    duplicate = line.clone();
    _results = [];
    for (i = _i = 1; _i <= 16; i = ++_i) {
      line.after(duplicate);
      line = duplicate;
      _results.push(duplicate = line.clone());
    }
    return _results;
  };
  stretchColumnsTo19 = function() {
    return $('table.go-board tr').each(function(i, row) {
      var cell, duplicate, _i, _results;

      cell = $(row).find(':nth-child(2)');
      duplicate = cell.clone();
      _results = [];
      for (i = _i = 1; _i <= 16; i = ++_i) {
        cell.after(duplicate);
        cell = duplicate;
        _results.push(duplicate = cell.clone());
      }
      return _results;
    });
  };
  stretchRowsTo19();
  return stretchColumnsTo19();
};

$(function() {
  var current_color;

  current_color = BLACK;
  scaleBoardTo19();
  return $('.go-board td').click(function() {
    var stone;

    stone = $(GO_STONE);
    if (current_color === BLACK) {
      stone.addClass('black');
      current_color = WHITE;
    } else {
      stone.addClass('white');
      current_color = BLACK;
    }
    return $(this).append(stone);
  });
});
